#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Plot generation script for the paper:
"Dynamic trajectory stability as a generalization criterion: Lyapunov's approach to the analysis of stochastic learning"

This script loads the results from 'synthetic_results.csv' (generated by the main experiment)
and produces the four figures presented in the paper:
    - ST_vs_inv_n_final.png   : S_T vs 1/n with linear fit
    - gap_vs_inv_n_final.png  : generalization gap vs 1/n
    - ST_vs_gap_final.png     : S_T vs gap with correlation
    - B_and_C_fixed.png       : B_T and C_eps vs n

It also prints the Pearson correlations between each index and the generalization gap.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

# Load the results
df = pd.read_csv('synthetic_results.csv')
n = df['n'].values
S_T = df['S_T'].values
gap = df['gap'].values
B_T = df['B_T'].values
C_eps = df['C_eps'].values

# Compute correlations
corr_S_gap, p_S = pearsonr(S_T, gap)
corr_B_gap, p_B = pearsonr(B_T, gap)
corr_C_gap, p_C = pearsonr(C_eps, gap)

print(f"Correlation S_T vs gap: {corr_S_gap:.3f} (p={p_S:.3f})")
print(f"Correlation B_T vs gap: {corr_B_gap:.3f} (p={p_B:.3f})")
print(f"Correlation C_eps vs gap: {corr_C_gap:.3f} (p={p_C:.3f})")

# Figure 1: S_T vs 1/n
plt.figure(figsize=(5, 4))
inv_n = 1.0 / n
plt.scatter(inv_n, S_T, color='green')
coeffs = np.polyfit(inv_n, S_T, 1)
poly = np.poly1d(coeffs)
inv_line = np.linspace(min(inv_n), max(inv_n), 100)
plt.plot(inv_line, poly(inv_line), 'r--',
         label=f'Slope={coeffs[0]:.3f}, r={np.corrcoef(inv_n, S_T)[0,1]:.3f}')
plt.xlabel('$1/n$')
plt.ylabel('$S_T$')
plt.legend()
plt.grid(True)
plt.title('S_T vs 1/n')
plt.tight_layout()
plt.savefig('ST_vs_inv_n_final.png', dpi=150)
plt.show()

# Figure 2: S_T vs generalization gap
plt.figure(figsize=(5, 4))
plt.scatter(S_T, gap, color='blue')
coeffs2 = np.polyfit(S_T, gap, 1)
poly2 = np.poly1d(coeffs2)
S_line = np.linspace(min(S_T), max(S_T), 100)
plt.plot(S_line, poly2(S_line), 'r--', label=f'corr = {corr_S_gap:.3f}')
plt.xlabel('$S_T$')
plt.ylabel('Generalization gap')
plt.legend()
plt.grid(True)
plt.title('S_T vs Generalization Gap')
plt.tight_layout()
plt.savefig('ST_vs_gap_final.png', dpi=150)
plt.show()

# Figure 3: B_T and C_eps vs n (side by side)
fig, axs = plt.subplots(1, 2, figsize=(10, 4))
axs[0].plot(n, B_T, 'o-', color='orange')
axs[0].set_xlabel('Sample size n')
axs[0].set_ylabel('$B_T$')
axs[0].set_title('Basin retention probability')
axs[0].grid(True)

axs[1].plot(n, C_eps, 'o-', color='red')
axs[1].set_xlabel('Sample size n')
axs[1].set_ylabel('$C_\varepsilon$')
axs[1].set_title('Concentration index')
axs[1].grid(True)

plt.tight_layout()
plt.savefig('B_and_C_fixed.png', dpi=150)   # consistent name with main experiment
plt.show()

# Figure 4: gap vs 1/n
plt.figure(figsize=(5, 4))
plt.scatter(inv_n, gap, color='purple')
coeffs3 = np.polyfit(inv_n, gap, 1)
poly3 = np.poly1d(coeffs3)
plt.plot(inv_line, poly3(inv_line), 'r--',
         label=f'corr = {np.corrcoef(inv_n, gap)[0,1]:.3f}')
plt.xlabel('$1/n$')
plt.ylabel('Generalization gap')
plt.legend()
plt.grid(True)
plt.title('Gap vs 1/n')
plt.tight_layout()
plt.savefig('gap_vs_inv_n_final.png', dpi=150)
plt.show()